repro:
  target: repro
  outputs:
    repro:
      threads: 50
      type: materialize
      host: "{{ env_var('MZ_HOST') }}"
      port: "{{ env_var('MZ_PORT', '6875') | int }}"
      user: "{{ env_var('MZ_USER') }}"
      password: "{{ env_var('MZ_PASSWORD') }}"
      database: "{{ env_var('MZ_DB') }}"
      cluster: "{{ env_var('MZ_CLUSTER') }}"
      schema: "{{ env_var('MZ_AUCTION_SCHEMA', 'public') }}"
